server:
  port: 8080
  servlet:
    context-path: /rating-system

spring:
  application:
    name: rating-system

  datasource:
    url: jdbc:postgresql://localhost:5432/rating_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: aduashvili2002ana@gmail.com
    password: stjj sqhp ufwp mrgd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: anaaduashvilianaaduashvilianaaduashvilianaaduashvili
  expiration-time: 86400000  # 24 hours in milliseconds
