services:
  db:
    image: 'postgres:latest'
    container_name: rating-system-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  redis:
    image: 'redis:latest'
    container_name: rating-system-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
volumes:
  pgdata:
  redisdata: